language: node_js
node_js:
  - "6"


deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        bucket: $AWS_BUCKET
        key: index.html
        #acl: public_read
        localdir: ./client
        application: MyApp
